/// Flutter icons IOSIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IOSIcons
///      fonts:
///       - asset: fonts/IOSIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IOSIcons {
  IOSIcons._();

  static const _kFontFam = 'IOSIcons';
  static const _kFontPkg = null;

  static const IconData arrow_up_arrow_down = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text_viewfinder = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square_and_arrow_up = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xmark_square = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
