/// Flutter icons AndroidIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AndroidIcons
///      fonts:
///       - asset: fonts/AndroidIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AndroidIcons {
  AndroidIcons._();

  static const _kFontFam = 'AndroidIcons';
  static const _kFontPkg = null;

  static const IconData account_box_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_scan_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eraser = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
