class Listsammlung {
  List<String> _gruende = [
    "Abfragegrund",
    "Vorgangsbearbeitung",
    "Strafverfolgung",
    "Ordnungswidrigkeiten",
    "Identitätsprüfung",
    "Amtshilfe",
    "Überprüfung an Kontrollstelle",
    "Aktenbereinigung",
    "Strafverfolgung gegen Betroffenen",
    "Strafverfolgung Dritter",
    "Strafvollstreckung",
    "Abwehr von -einer im Einzelfall bestehenden- Gefahr(en)",
    "Datenpflege",
    "Grunddatenauskunft",
    "Fahndung, Grenzfahndung, Kontrollstelle",
    "Sonstige Anlässe",
    "Überwachung Straßenverkehr",
    "Nichtbeachten Anhalteaufforderung oder Unfallflucht",
    "Aufgefundene oder verkehrsbehindernde Fahrzeuge",
    "Verdacht Diebstahl oder missbräuchliche Nutzung",
    "Auswertung",
    "Test",
    "Ausbildung",
    "Verwaltungsmaßnahmen Straßenverkehr (i.Z.m. Berechtigung z. Führen von Fz.)",
    "Verhinderung von Straftaten",
    "Verfolgung sonstiger Verstöße",
    "Identifizierung (Art.20) - Strafverfolgung gegen Betroffenen",
    "Identifizierung (Art.20) - Strafverfolgung Dritter",
    "Identifizierung (Art.20) - Strafvollstreckung",
    "Identifizierung (Art.20) - Abwehr von Gefahren",
    "Verifizierung (Art.19) - Strafverfolgung gegen Betroffenen",
    "Verifizierung (Art.19) - Strafverfolgung Dritter",
    "Verifizierung (Art.19) - Strafvollstreckung",
    "Verifizierung (Art.19) - Abwehr von Gefahren",
    "Nur VIS- Verifizierung im Hoheitsgebiet der Mitgliedstaaten (Art.19)",
    "Nur VIS- Identifizierung im Hoheitsgebiet der Mitgliedstaaten (Art.20)",
    "Schadensregulierung",
    "Andere behördliche Aufgaben",
    "ausländerrechtliche Aufgaben",
    "grenzpolizeilicher Schutz",
    "asylrechtliche Aufgaben",
    "Vollzug WaffG",
    "Polizeiliche Rechtshilfe",
    "Amts- und Rechtshilfe Zoll",
    "Zollamtliche Überwachung",
    "Aufgaben nach §3 Abs. 1 Nr. 1 BVerfSchG",
    "Aufgaben nach §3 Abs. 1 Nr. 2 BVerfSchG",
    "Aufgaben nach §3 Abs. 1 Nr. 3 BVerfSchG",
    "Aufgaben nach §3 Abs. 2 BVerfSchG",
    "Aufgaben nach §3 Abs. 1 Nr. 4 BVerfSchG",
    "Aufgaben nach VerfSchG der Länder",
    "Aufgaben nach MADG",
    "Aufgaben nach BNDG",
    "Auskunftsanspruch des Betroffenen",
    "Vollzug KWKG",
    "Justizielle Rechtshilfe",
    "Diplomatische Rechtshilfe",
    "Gefahr für Leib, Leben, Gesundheit oder Freiheit einer Person- NWRG",
    "Aufgaben nach BVerfSchG",
    "Grenzkontrolle",
    "Ermittlungsverfahren wegen Straftaten",
    "Verifizierung an Außengrenzübergangsstellen (Art.18) -grenzpolizeilicher Schutz",
    "Identifizierung (Art. 20) - grenzpolizeilicher Schutz",
    "Steuerfahndung",
    "Datenschutzrechtliches Auskunfts-/Löschungsersuchen",
    "Aufgaben nach § 28 Abs. 1 S.2 Nr.2 GwG",
    "Verkehrskontrolle",
    "Sonstiges",
    "Rechtspflege (1. Auskunftsstufe)",
    "Aufgaben nach dem 2. und 3. Sozialgesetzbuch (SGB II u. III)",
    "Aufgaben für erforderliche Gesundheitsuntersuchungen",
    "Aufgaben des öffentlichen Gesundheitsdienstes",
    "Aufgaben nach dem 8. Sozialgesetzbuch (SGB VIII)",
    "Aufgaben nach dem Bundesmeldegesetz",
    "Beobachtung terroristischer Bestrebungen",
    "humanitäre oder soziale Aufgaben",
    "Sonstige nichtöffentliche Stelle nach § 27 AZRG",
    "Aufgaben nach dem Bundesverfassungsschutzgesetz",
    "Aufgabe nach §3 Abs.1 Nr.1 BfV-Gesetz",
    "Aufgabe nach §3 Abs.1 Nr.2 BfV-Gesetz",
    "Aufgabe nach §3 Abs.1 Nr.3 BfV-Gesetz",
    "Aufgabe nach §3 Abs.2 BfV-Gesetz",
    "Aufgaben nach dem MAD-Gesetz",
    "Aufgabe nach §1 Abs.1 Nr.2 MAD-Gesetz",
    "Aufgabe nach §1 Abs.3 MAD-Gesetz",
    "Aufgaben nach dem BND-Gesetz",
    "Aufgabe nach §2 Abs.1 Nr.2 BND-Gesetz",
    "Aufgabe nach §2 Abs.1 Nr.3 BND-Gesetz",
    "Aufgabe nach §2 Abs.1 Nr.4 BND-Gesetz",
    "Erfüllung völkerrechtlicher Verträge (Vollauskunft)",
    "Rechtspflege (2. Auskunftsstufe)",
    "Zuverlässigkeitsprüfung nach § 7 LuftSichG o. § 12b AtomG",
    "Aufgaben nach dem 2. Oder 12. Sozialgesetzbuch (SGB II o. XII)",
    "Aufgaben nach dem AsylbLG",
    "Aufgaben der Migration und Integration",
    "Konsultation nach § 73 Abs. 1 a AufenthG",
    "Aufgaben bei Zulassung und Überwachung der Ausländerbeschäftigung",
    "Datenpflege gesperrter Datensätze",
    "Aufgaben nach § 28 Absatz 1 Satz 2 Nummer 2 des Geldwäschegesetzes",
    "Rechtspflege (3. Auskunftsstufe, nur BVA)",
    "Zuverlässigkeits- und Sicherheitsüberprüfung (ZSÜ)",
    "Visumentscheidung an Grenze (Art. 8-10, 12-14) - 01: ausländerrechtliche Aufgaben",
    "Prüfung Visumsantrag an Grenze (Art.15) - 01: ausländerrechtliche Aufgaben",
    "Änderung von Daten an Grenze (Art.24) - 21: Datenpflege",
    "Verifizierung an Außengrenzübergangsstellen (Art.18) - 03: grenzpolizeilicher Schutz",
    "Verifizierung im Hoheitsgebiet der Mitgliedstaaten (Art.19) - 01: ausländerrechtliche Aufgabe",
    "Verifizierung im Hoheitsgebiet der Mitgliedstaaten (Art.19) - 01: ausländerrechtliche Aufgaben",
    "Identifizierung (Art.20) im Hoheitsgebiet der Mitgliedstaaten - 01: ausländerrechtliche Aufgaben",
    "Identifizierung (Art.20) an Außengrenzübergangsstellen - 03: grenzpolizeilicher Schutz",
    "Identitätsfeststellung §15 Abs.3 AZR-Gesetz",
    "Unterstützung der Zollfahndungsämter",
    "Ermittlungen des Zollkriminalamtes",
    "Bekaempfung illegaler Beschaeftigung",
    "Feststellung Eigenschaft Deutscher",
    "Feststellung Aussiedler- oder Spätaussiedlereigenschaft",
    "Visaverfahren",
    "Identifizierung (Art.20) im Hoheitsgebiet der Mitgliedstaaten -- 01: ausländerrechtliche Aufgaben",
    "Aufgaben nach dem 6. Sozialgesetzbuch (SGB VI)",
    "Beratung und Bearbeitung von Einbürgerungsanträgen",
    "eingeschränkte Grunddatenauskunft",
    "Bestimmung der Zuständigkeit für Asylanträge (Art.21) - 02: asylrechtliche Aufgaben",
    "Prüfung Asylantrag (Art.22) - 02: asylrechtliche Aufgaben",
  ];

  List<String> staatsangehoerigkeiten = [
    "afghanisch",
    "ägyptisch",
    "albanisch",
    "algerisch",
    "us-amerikanisch",
    "andorranisch",
    "angolanisch",
    "antiguanisch",
    "äquatorialguineisch",
    "argentinisch",
    "armenisch",
    "aserbaidschanisch",
    "äthiopisch",
    "australisch",
    "bahamaisch",
    "bahrainisch",
    "bangladeschisch",
    "barbadisch",
    "belgisch",
    "belizisch",
    "beninisch",
    "bhutanisch",
    "bolivianisch",
    "bosnisch-herzegowinisch",
    "botsuanisch",
    "brasilianisch",
    "britisch",
    "bruneiisch",
    "bulgarisch",
    "burkinisch",
    "burundisch",
    "chilenisch",
    "chinesisch",
    "chinesisch (Taiwan)",
    "costaricanisch",
    "dänisch",
    "Vereinigten Arabischen Emirate, der",
    "dominicanisch",
    "dominikanisch",
    "dschibutisch",
    "ecuadorianisch",
    "eritreisch",
    "estnisch",
    "fidschianisch",
    "finnisch",
    "französisch",
    "gabunisch",
    "gambisch",
    "georgisch",
    "ghanaisch",
    "grenadisch",
    "griechisch",
    "guatemaltekisch",
    "guyanisch",
    "guineisch (Guinea-Bisseau)",
    "guineisch",
    "haitianisch",
    "honduranisch",
    "indisch",
    "indonesisch",
    "irakisch",
    "iranisch",
    "irisch",
    "isländisch",
    "israelisch",
    "italienisch",
    "ivorisch",
    "jamaikanisch",
    "japanisch",
    "jemenitisch",
    "jordanisch",
    "jugoslawisch (ehem.)",
    "kamerunisch",
    "kambodschanisch",
    "kanadisch",
    "kapverdisch",
    "kasachisch",
    "katarisch",
    "kenianisch",
    "kirgisisch",
    "kiribatisch",
    "kolumbianisch",
    "komorisch",
    "kongolesisch",
    "koreanisch (nord)",
    "koreanisch",
    "kroatisch",
    "kubanisch",
    "kuwaitisch",
    "laotisch",
    "lesothisch",
    "lettisch",
    "libanesisch",
    "liberianisch",
    "libysch",
    "liechtensteinisch",
    "litauisch",
    "lucianisch",
    "luxemburgisch",
    "madagassisch",
    "mazedonisch",
    "malawisch",
    "malaysisch",
    "maledivisch",
    "malisch",
    "maltesisch",
    "mareanisch",
    "marokkanisch",
    "marshallisch",
    "mauretanisch",
    "mauritisch",
    "mexikanisch",
    "mikronesisch",
    "moldauisch",
    "monegassisch",
    "mongolisch",
    "mosambikanisch",
    "myanmarisch",
    "namibisch",
    "nauruisch",
    "nepalesisch",
    "neuseeländisch",
    "nicaraguanisch",
    "niederländisch",
    "nigerianisch",
    "nigrisch",
    "norwegisch",
    "omanisch",
    "österreichisch",
    "pakistanisch",
    "palauisch",
    "panamaisch",
    "papua-neuguineisch",
    "paraguayisch",
    "peruanisch",
    "philippinisch",
    "polnisch",
    "portugiesisch",
    "ruandisch",
    "rumänisch",
    "russisch",
    "salomonisch",
    "salvadorianisch",
    "sambisch",
    "samoanisch",
    "san-marinesisch",
    "santomeisch",
    "saudi-arabisch",
    "schwedisch",
    "schweizerisch",
    "senegalesisch",
    "serbisch -Altbestand-",
    "seychellisch",
    "sierraleonisch",
    "simbabwisch",
    "singapurisch",
    "slowakisch",
    "slowenisch",
    "somalisch",
    "sowjetisch",
    "spanisch",
    "srilankisch",
    "südafrikanisch",
    "sudanesisch (incl. Südsudan)",
    "surinamisch",
    "swasiländisch",
    "syrisch",
    "tadschikisch",
    "tansanisch",
    "thailändisch",
    "togoisch",
    "tongaisch",
    "tschadisch",
    "tschechisch",
    "tschechoslowakisch -ehemals-",
    "tunesisch",
    "türkisch",
    "turkmenisch",
    "tuvaluisch",
    "ugandisch",
    "ukrainisch",
    "ungarisch",
    "uruguayisch",
    "usbekisch",
    "vanuatuisch",
    "vatikanisch",
    "venezolanisch",
    "vietnamesisch",
    "vincentisch",
    "St. Kitts und Nevis, von",
    "Trinidad und Tobago, von",
    "belarussisch",
    "kongolesisch (ehem. Zaire)",
    "zentralafrikanisch",
    "zyprisch",
    "Aruba",
    "Bophuthatswana",
    "Ciskei",
    "neuseeländisch, Cookinseln",
    "Hong Kong (GB)",
    "Hong Kong (China)",
    "chinesisch, Macau",
    "niuisch",
    "Sonstige/keine Angaben",
    "Palästina",
    "Paz. Inseln unter Treuhandverwaltung",
    "Nicht Deutsch",
    "Staatenlos",
    "Transkei",
    "ungeklärt",
    "UNO",
    "Venda",
    "Altbestand",
    "Europäische Union",
    "britisch, Alderney",
    "dänisch, Faroeer",
    "chinesisch, Hongkong",
    "britisch, Gibraltar",
    "britisch, Guernsey",
    "britisch, Jersey",
    "britisch, Isle of Man",
    "Niederländische Antillen",
    "Schleswig-Holstein",
    "Hamburg",
    "Niedersachsen",
    "Bremen",
    "Nordrhein-Westfalen",
    "Hessen",
    "Rheinland-Pfalz",
    "Baden-Württemberg",
    "Bayern",
    "Saarland",
    "Berlin",
    "Brandenburg",
    "Mecklenburg-Vorpommern",
    "Sachsen",
    "Sachsen-Anhalt",
    "Thüringen",
    "britisch abhängige Gebiete in Europa",
    "übriges Europa",
    "britisch abhängige Gebiete in Afrika",
    "übriges Afrika",
    "britisch abhängige Gebiete in Amerika",
    "übriges Amerika",
    "britisch abhängige Gebiete in Australien oder Ozeanien",
    "JEMEN, DEM. VOLKSREPUBLIK (für Migration)",
    "übriges Ozeanien",
    "Timor-Leste, von",
    "von/nach See",
    "serbisch-montenegrinisch",
    "unbekanntes Ausland",
    "britisch abhängige Gebiete in Asien",
    "übriges Asien",
    "Flüchtling (sonstiger)",
    "Flüchtling gem. Konvent 1954",
    "Intern. Kommitee Rotes Kreuz",
    "Palästinens. Autonomiegebiete",
    "UNHCR",
    "britisch, Anguilla",
    "amerikanisch samoa",
    "britisch, Bermuda",
    "britisch, Cayman-Inseln",
    "britisch, England",
    "Guam",
    "St. Lucia - Doppelerfassung-",
    "britisch, Montserrat",
    "britisch, Nordirland",
    "puertoricanisch",
    "britisch, Schottland",
    "tahitianisch",
    "chinesisch (Taipei)",
    "britisch, Virgin Islands",
    "us-amerikanisch (Virgin Islands)",
    "britisch, walisisch",
    "britisch, Turks- and Caicos Islands",
    "neu-kaledonisch",
    "Heimatloser Ausländer",
    "serbisch (einschl. Kosovo)",
    "montenegrinisch",
    "kosovarisch",
    "serbisch",
    "us-amerikanisch, Amerikanisch-Ozeanien",
    "britisch, Antarktis-Territorium",
    "norwegisch, Bouvetinsel",
    "britisch, Britisches Territorium im Indischen Ozean",
    "britisch, Falklandinseln",
    "französisch, Französisch-Guyana",
    "französisch, Französisch-Polynesien",
    "französisch, Französisch-südliche Territorien",
    "französisch, Guadeloupe",
    "australisch, Heard und McDonaldinseln",
    "australisch, Kokosinseln",
    "französisch, Martinique",
    "französisch, Mayotte",
    "britisch, Pitcairn",
    "französisch, Réunion",
    "britisch, St.Helena",
    "französisch, St.Pierre und Miquelon",
    "britisch, Südgeorgien und die südlichen Sandwichinseln",
    "norwegisch, Svalbard und Jan Mayen",
    "neuseeländisch, Tokelau",
    "australisch, Norfolkinsel",
    "dänisch, Grönland",
    "französisch, Wallis und Futuna",
    "australisch, Weihnachtsinsel",
    "Westsahara",
    "finnisch, Aland Inseln",
    "südsudanesisch",
    "sudanesisch (ohne Südsudan)",
    "Jugoslawien (Gesamtjugoslawien)",
    "Dänisch abhängige Gebiete in Europa",
    "Dänisch abhängige Gebiete in Amerika",
    "Französisch abhängige Gebiete in Afrika",
    "Französisch abhängige Gebiete in Amerika",
    "Französisch abhängige Gebiete in AOA",
    "Niederländisch abhängige Gebiete in Amerika",
    "Norwegisch abhängige Gebiete in Europa",
    "Norwegisch abhängige Gebiete in AOA",
    "Spanisch abhängige Gebiete in Afrika",
    "Argentinisch abhängige Gebiete in AOA",
    "Chilenisch abhängige Gebiete in AOA",
    "US-abhängige Gebiete in Amerika",
    "US-abhängige Gebiete in Asien",
    "US-abhängige Gebiete in AOA",
    "Australisch abhängige Gebiete in AOA",
    "Neuseeländisch abhängige Gebiete in AOA",
    "niederländisch, Curacao",
    "niederländisch, St. Martin",
    "britisch, Britische Überseegebiete",
    "niederländisch, Bonaire",
    "AFISWeb/BIOSP",
    "USA/FBI",
    "USA/DHS",
    "sansibarisch",
    "palästinensisch",
    "deutsch",
  ];

  List<String> rollen = [
    "Tatverdaechtiger",
    "BetroffenerOWI",
    "Stoerer",
    "Verantwortlicher",
    "Betroffener",
    "Beteiligter",
    "Asylbewerber",
    "Verstorbener",
    "Vermisster",
    "Hilfloser",
    "Festgenommener",
    "Gesuchter",
    "VorlaeufigUntergebrachter",
    "HalterEigentuemerBeissTier",
    "Schiffsfuehrer",
    "Schiffseigner",
    "Lotse",
    "Geschaedigter",
    "BetreiberDerAlarmanlage",
    "SonstigerGeschaedigter",
    "Anzeigender",
    "Mitteiler",
    "Zeuge",
    "MitreisendesKind",
    "BetroffenerVorfuehrungsbefehl",
    "BetroffenerSchuldner",
    "AngehoertesKind",
    "BeteiligterSchiffsunfall",
    "EDBehandelter",
    "Finder",
    "HalterEigentuemGeschaedTier",
    "InhaftiertePerson",
    "Ueberbringer",
    "BetroffenerTOE",
    "Antragsteller",
    "AnwesenderMitarbeiter",
    "BetroffenerDerDNAMassnahme",
    "Gefaehrder",
    "Gefaehrdeter",
    "Hinweisgeber",
    "Kontaktperson",
    "SonstigerBeteiligter",
    "VerletztePerson",
    "VorgeladenerTatverdaechtiger",
    "VorgeladenerZeuge",
    "Beschuldigter",
    "Reiter",
    "BetroffenePerson",
    "BetroffenerSicherstBeschlagn",
    "BetroffenerDerDurchsuchung",
    "Fahrzeugfuehrer",
    "Fussgaenger",
    "VorgeladRechtlVertreter",
    "Mittaeter",
    "NeutralerSpurenverursacher",
    "GetoetetePerson",
    "Radfahrer",
    "VorgeladenesKind",
    "SonstigerVerkehrsteilnehmer",
    "BetroffenerEinerMassnahme",
    "EDZuBehandelndePerson",
    "GeschaedigterDesBrandes",
    "DNAUntersBetroffenePerson",
    "VorzuladenePerson",
    "MeldepflichtigerHaftverschon",
    "BetroffenerAltersgutachten",
    "BetroffenerPHW",
  ];

  List<String> laendernamen = [
    "Afghanistan",
    "Ägypten",
    "Albanien",
    "Algerien",
    "Vereinigte Staaten von Amerika",
    "Andorra",
    "Angola",
    "Antigua und Barbuda",
    "Äquatorialguinea",
    "Argentinien",
    "Armenien",
    "Aserbaidschan",
    "Äthiopien",
    "Australien",
    "Bahamas",
    "Bahrain",
    "Bangladesch",
    "Barbados",
    "Belgien",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivien, Plurinationaler Staat",
    "Bosnien und Herzegowina",
    "Botsuana",
    "Brasilien",
    "Vereinigtes Königreich",
    "Brunei Darussalam",
    "Bulgarien",
    "Burkina Faso",
    "Burundi",
    "Chile",
    "China",
    "Taiwan",
    "Costa Rica",
    "Dänemark",
    "Vereinigte Arabische Emirate",
    "Dominica",
    "Dominikanische Republik",
    "Dschibuti",
    "Ecuador",
    "Eritrea",
    "Estland",
    "Fidschi",
    "Finnland",
    "Frankreich",
    "Gabun",
    "Gambia",
    "Georgien",
    "Ghana",
    "Grenada",
    "Griechenland",
    "Guatemala",
    "Guyana",
    "Guinea-Bissau",
    "Guinea",
    "Haiti",
    "Honduras",
    "Indien",
    "Indonesien",
    "Irak",
    "Iran, Islamische Volksrepublik",
    "Irland",
    "Island",
    "Israel",
    "Italien",
    "Cote d Ivoire",
    "Jamaika",
    "Japan",
    "Jemen, Republik",
    "Jordanien",
    "Jugoslawien (ehem.)",
    "Kamerun",
    "Kambodscha",
    "Kanada",
    "Kap Verde",
    "Kasachstan",
    "Katar",
    "Kenia",
    "Kirgisistan",
    "Kiribati",
    "Kolumbien",
    "Komoren",
    "Kongo",
    "Korea, Demokratische Volksrepublik",
    "Korea, Republik",
    "Kroatien",
    "Kuba",
    "Kuwait",
    "Laos, Demokratische Volksrepublik",
    "Lesotho",
    "Lettland",
    "Libanon",
    "Liberia",
    "Libyen",
    "Liechtenstein",
    "Litauen",
    "Santa Lucia",
    "Luxemburg",
    "Madagaskar",
    "Mazedonien",
    "Malawi",
    "Malaysia",
    "Malediven",
    "Mali",
    "Malta",
    "Nördliche Marianen",
    "Marokko",
    "Marshallinseln",
    "Mauretanien",
    "Mauritius",
    "Mexiko",
    "Mikronesien, Föderierte Staaten von",
    "Moldau, Republik",
    "Monaco",
    "Mongolei",
    "Mosambik",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Neuseeland",
    "Nicaragua",
    "Niederlande",
    "Nigeria",
    "Niger",
    "Norwegen",
    "Oman",
    "Österreich",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua-Neuguinea",
    "Paraguay",
    "Peru",
    "Philippinen",
    "Polen",
    "Portugal",
    "Ruanda",
    "Rumänien",
    "Russische Föderation",
    "Salomonen",
    "El Salvador",
    "Sambia",
    "Samoa",
    "San Marino",
    "Sao Tome und Principe",
    "Saudi-Arabien",
    "Schweden",
    "Schweiz",
    "Senegal",
    "Serbien",
    "Seyschellen",
    "Sierra Leone",
    "Simbabwe",
    "Singapur",
    "Slowakische Republik",
    "Slowenien",
    "Somalia",
    "Sowjetunion (ehem.)",
    "Spanien",
    "Sri Lanka",
    "Südafrika",
    "Sudan",
    "Surinam",
    "Swasiland",
    "Syrien, Arabische Republik",
    "Tadschikistan",
    "Tansania, Vereinigte Republik",
    "Thailand",
    "Togo",
    "Tonga",
    "Tschad",
    "Tschechische Republik",
    "Tschechoslowakei (ehem.)",
    "Tunesien",
    "Türkei",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "Ungarn",
    "Uruguay",
    "Usbekistan",
    "Vanuatu",
    "Vatikanstaat",
    "Venezuela",
    "Vietnam",
    "St. Vincent und die Grenadinen",
    "St. Kitts und Nevis",
    "Trinidad und Tobago",
    "Belarus",
    "Kongo, Demokratische Republik",
    "Zentralafrikanische Republik",
    "Zypern",
    "Aruba",
    "Bophuthatswana",
    "Ciskei",
    "Cook-Inseln",
    "Hong Kong (GB)",
    "Hong Kong (China)",
    "Macao",
    "Niue-Inseln",
    "keine Angaben",
    "Palästinensisches Gebiet",
    "Pazifikinseln (ehem.)",
    "Nicht Deutsch",
    "Staatenlos",
    "Transkei",
    "unbekannt",
    "UNO",
    "Venda",
    "Altbestand, nicht zur Erfassung",
    "Europäische Union",
    "Alderney",
    "Faroeer",
    "Hongkong",
    "Gibraltar",
    "Guernsey",
    "Jersey",
    "Isle of Man",
    "Niederländische Antillen",
    "Schleswig-Holstein",
    "Hamburg",
    "Niedersachsen",
    "Bremen",
    "Nordrhein-Westfalen",
    "Hessen",
    "Rheinland-Pfalz",
    "Baden-Württemberg",
    "Bayern",
    "Saarland",
    "Berlin",
    "Brandenburg",
    "Mecklenburg-Vorpommern",
    "Sachsen",
    "Sachsen-Anhalt",
    "Thüringen",
    "britisch abhängige Gebiete in Europa",
    "übriges Europa",
    "britisch abhängige Gebiete in Afrika",
    "übriges Afrika",
    "britisch abhängige Gebiete in Amerika",
    "übriges Amerika",
    "britisch abhängige Gebiete in Australien oder Ozeanien",
    "JEMEN, DEM. VOLKSREPUBLIK (nur für Migration)",
    "übriges Ozeanien",
    "Timor-Leste",
    "von/nach See",
    "Serbien und Montenegro (ehem.)",
    "unbekanntes Ausland",
    "britisch abhängige Gebiete in Asien",
    "übriges Asien",
    "Flüchtling (sonstiger)",
    "Flüchtling gem. Konvent 1954",
    "Intern. Kommitee Rotes Kreuz",
    "Palästinens. Autonomiegebiete",
    "UNHCR",
    "Anguilla",
    "Amerikanisch Samoa",
    "Bermuda",
    "Cayman-Inseln",
    "England",
    "Guam",
    "St. Lucia",
    "Montserrat",
    "Nordirland",
    "Puerto Rico",
    "Schottland",
    "Tahiti",
    "Taipei",
    "Britische Virgin Islands",
    "US Virgin Islands",
    "Wales",
    "Turks- and Caicos Islands",
    "Neu-Kaledonien",
    "Heimatloser Ausländer",
    "Serbien (einschl. Kosovo)",
    "Montenegro",
    "Kosovo, Republik",
    "Serbien, Republik",
    "Amerikanisch-Ozeanien",
    "Antarktis-Territorium",
    "Bouvetinsel",
    "Britisches Territorium im Indischen Ozean",
    "Falklandinseln",
    "Französisch-Guyana",
    "Französisch-Polynesien",
    "Französisch-südliche Territorien",
    "Guadeloupe",
    "Heard und McDonaldinseln",
    "Kokosinseln",
    "Martinique",
    "Mayotte",
    "Pitcairn",
    "Réunion",
    "St.Helena",
    "St.Pierre und Miquelon",
    "Südgeorgien und die südlichen Sandwichinseln",
    "Svalbard und Jan Mayen",
    "Tokelau",
    "Norfolkinsel",
    "Grönland",
    "Wallis und Futuna",
    "Weihnachtsinsel",
    "Westsahara",
    "Aland Inseln",
    "Südsudan, Republik",
    "Sudan, Republik (ohne Südsudan)",
    "Jugoslawien (Gesamtjugoslawien)",
    "Dänisch abhängige Gebiete in Europa",
    "Dänisch abhängige Gebiete in Amerika",
    "Französisch abhängige Gebiete in Afrika",
    "Französisch abhängige Gebiete in Amerika",
    "Französisch abhängige Gebiete in AOA",
    "Niederländisch abhängige Gebiete in Amerika",
    "Norwegisch abhängige Gebiete in Europa",
    "Norwegisch abhängige Gebiete in AOA",
    "Spanisch abhängige Gebiete in Afrika",
    "Argentinisch abhängige Gebiete in AOA",
    "Chilenisch abhängige Gebiete in AOA",
    "US-abhängige Gebiete in Amerika",
    "US-abhängige Gebiete in Asien",
    "US-abhängige Gebiete in AOA",
    "Australisch abhängige Gebiete in AOA",
    "Neuseeländisch abhängige Gebiete in AOA",
    "Curacao",
    "St.Martin (niederländisch)",
    "Britische Überseegebiete",
    "Bonaire",
    "AFISWeb/BIOSP",
    "Federal Bureau of Investigation",
    "Department of Homeland Security",
    "Sansibar",
    "Palästinensische Gebiete",
    "Deutschland",
    "unbekannt (Doppelerfassung)",
  ];

  List<String> geschlechter = [
    "männlich",
    "weiblich",
    "unbekannt",
    "divers",
    "divers-alt-",
    "ohne Angabe",
  ];

  List<String> getAbfragegruende() {
    return _gruende;
  }

  List<String> getlaenderNamen() {
    return laendernamen;
  }

  List<String> getGeschlecht() {
    return geschlechter;
  }

  List<String> getStaatsangehoerigkeiten() {
    return staatsangehoerigkeiten;
  }

  List<String> getRollen() {
    return rollen;
  }
}
