/// Flutter icons GridIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GridIcons
///      fonts:
///       - asset: fonts/GridIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GridIcons {
  GridIcons._();

  static const _kFontFam = 'GridIcons';
  static const _kFontPkg = null;

  static const IconData customer_insight_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData binder = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_card = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer_insight = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData driving_guidelines = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData find_user_male = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
